/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './scholar-form.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './scholar.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/forms/src/directives/ng_form';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/ng_model';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/forms/src/directives/control_value_accessor';
import * as import17 from '@angular/forms/src/directives/ng_control';
import * as import18 from '@angular/forms/src/directives/control_container';
var renderType_ScholarFormComponent_Host:import0.RenderComponentType = (null as any);
class _View_ScholarFormComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScholarFormComponent_0_4:import3.ScholarFormComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarFormComponent_Host0,renderType_ScholarFormComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('scholar-form',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScholarFormComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScholarFormComponent_0_4 = new import3.ScholarFormComponent(this.parentInjector.get(import8.ScholarService));
    this._appEl_0.initComponent(this._ScholarFormComponent_0_4,[],compView_0);
    compView_0.create(this._ScholarFormComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ScholarFormComponent) && (0 === requestNodeIndex))) { return this._ScholarFormComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScholarFormComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScholarFormComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ScholarFormComponent_Host === (null as any))) { (renderType_ScholarFormComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ScholarFormComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScholarFormComponentNgFactory:import10.ComponentFactory<import3.ScholarFormComponent> = new import10.ComponentFactory<import3.ScholarFormComponent>('scholar-form',viewFactory_ScholarFormComponent_Host0,import3.ScholarFormComponent);
const styles_ScholarFormComponent:any[] = [];
var renderType_ScholarFormComponent:import0.RenderComponentType = (null as any);
class _View_ScholarFormComponent0 extends import1.AppView<import3.ScholarFormComponent> {
  _el_0:any;
  _NgForm_0_3:import11.NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import12.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _DefaultValueAccessor_6_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_6_4:any[];
  _NgModel_6_5:import14.NgModel;
  _NgControl_6_6:any;
  _NgControlStatus_6_7:import12.NgControlStatus;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _NgModel_13_5:import14.NgModel;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import12.NgControlStatus;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _DefaultValueAccessor_20_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_20_4:any[];
  _NgModel_20_5:import14.NgModel;
  _NgControl_20_6:any;
  _NgControlStatus_20_7:import12.NgControlStatus;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _DefaultValueAccessor_31_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_31_4:any[];
  _NgModel_31_5:import14.NgModel;
  _NgControl_31_6:any;
  _NgControlStatus_31_7:import12.NgControlStatus;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _DefaultValueAccessor_41_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_41_4:any[];
  _NgModel_41_5:import14.NgModel;
  _NgControl_41_6:any;
  _NgControlStatus_41_7:import12.NgControlStatus;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  _DefaultValueAccessor_50_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_50_4:any[];
  _NgModel_50_5:import14.NgModel;
  _NgControl_50_6:any;
  _NgControlStatus_50_7:import12.NgControlStatus;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _DefaultValueAccessor_57_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_57_4:any[];
  _NgModel_57_5:import14.NgModel;
  _NgControl_57_6:any;
  _NgControlStatus_57_7:import12.NgControlStatus;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarFormComponent0,renderType_ScholarFormComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._NgForm_0_3 = new import11.NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3;
    this._NgControlStatusGroup_0_5 = new import12.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','form-group');
    this._el_3 = this.renderer.createElement(this._el_2,'label',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Name',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','form-control');
    this.renderer.setElementAttribute(this._el_6,'name','name');
    this.renderer.setElementAttribute(this._el_6,'type','text');
    this._DefaultValueAccessor_6_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_6));
    this._NG_VALUE_ACCESSOR_6_4 = [this._DefaultValueAccessor_6_3];
    this._NgModel_6_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_6_4);
    this._NgControl_6_6 = this._NgModel_6_5;
    this._NgControlStatus_6_7 = new import12.NgControlStatus(this._NgControl_6_6);
    this._text_7 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','form-group');
    this._el_10 = this.renderer.createElement(this._el_9,'label',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Position',(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_9,'input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-control');
    this.renderer.setElementAttribute(this._el_13,'name','position');
    this.renderer.setElementAttribute(this._el_13,'type','text');
    this._DefaultValueAccessor_13_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3];
    this._NgModel_13_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._NgModel_13_5;
    this._NgControlStatus_13_7 = new import12.NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-group');
    this._el_17 = this.renderer.createElement(this._el_16,'label',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Place',(null as any));
    this._text_19 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_16,'input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','form-control');
    this.renderer.setElementAttribute(this._el_20,'name','place');
    this.renderer.setElementAttribute(this._el_20,'type','text');
    this._DefaultValueAccessor_20_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_20));
    this._NG_VALUE_ACCESSOR_20_4 = [this._DefaultValueAccessor_20_3];
    this._NgModel_20_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_20_4);
    this._NgControl_20_6 = this._NgModel_20_5;
    this._NgControlStatus_20_7 = new import12.NgControlStatus(this._NgControl_20_6);
    this._text_21 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','row');
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','col-sm-8');
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','form-group');
    this._el_28 = this.renderer.createElement(this._el_27,'label',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Contact',(null as any));
    this._text_30 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_27,'input',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','form-control');
    this.renderer.setElementAttribute(this._el_31,'name','contact');
    this.renderer.setElementAttribute(this._el_31,'type','email');
    this._DefaultValueAccessor_31_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_31));
    this._NG_VALUE_ACCESSOR_31_4 = [this._DefaultValueAccessor_31_3];
    this._NgModel_31_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_31_4);
    this._NgControl_31_6 = this._NgModel_31_5;
    this._NgControlStatus_31_7 = new import12.NgControlStatus(this._NgControl_31_6);
    this._text_32 = this.renderer.createText(this._el_27,'\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_23,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','col-sm-4');
    this._text_36 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group');
    this._el_38 = this.renderer.createElement(this._el_37,'label',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Country',(null as any));
    this._text_40 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_37,'input',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','form-control');
    this.renderer.setElementAttribute(this._el_41,'name','country');
    this.renderer.setElementAttribute(this._el_41,'type','text');
    this._DefaultValueAccessor_41_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_41));
    this._NG_VALUE_ACCESSOR_41_4 = [this._DefaultValueAccessor_41_3];
    this._NgModel_41_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_41_4);
    this._NgControl_41_6 = this._NgModel_41_5;
    this._NgControlStatus_41_7 = new import12.NgControlStatus(this._NgControl_41_6);
    this._text_42 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','form-group');
    this._el_47 = this.renderer.createElement(this._el_46,'label',(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'Detail',(null as any));
    this._text_49 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_46,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','form-control');
    this.renderer.setElementAttribute(this._el_50,'name','detail');
    this._DefaultValueAccessor_50_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_50));
    this._NG_VALUE_ACCESSOR_50_4 = [this._DefaultValueAccessor_50_3];
    this._NgModel_50_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_50_4);
    this._NgControl_50_6 = this._NgModel_50_5;
    this._NgControlStatus_50_7 = new import12.NgControlStatus(this._NgControl_50_6);
    this._text_51 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','form-group');
    this._el_54 = this.renderer.createElement(this._el_53,'label',(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Misc',(null as any));
    this._text_56 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_53,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','form-control');
    this.renderer.setElementAttribute(this._el_57,'name','misc');
    this._DefaultValueAccessor_57_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_57));
    this._NG_VALUE_ACCESSOR_57_4 = [this._DefaultValueAccessor_57_3];
    this._NgModel_57_5 = new import14.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_57_4);
    this._NgControl_57_6 = this._NgModel_57_5;
    this._NgControlStatus_57_7 = new import12.NgControlStatus(this._NgControl_57_6);
    this._text_58 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_59 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','form-group');
    this._text_61 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','btn btn-outline-primary');
    this.renderer.setElementAttribute(this._el_62,'type','submit');
    this._text_63 = this.renderer.createText(this._el_62,'Submit',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    const subscription_0:any = this._NgForm_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_6,'input',this.eventHandler(this._handle_input_6_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_6,'blur',this.eventHandler(this._handle_blur_6_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_1.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_20,'input',this.eventHandler(this._handle_input_20_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_20,'blur',this.eventHandler(this._handle_blur_20_1.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_31,'input',this.eventHandler(this._handle_input_31_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_31,'blur',this.eventHandler(this._handle_blur_31_1.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    var disposable_11:Function = this.renderer.listen(this._el_41,'input',this.eventHandler(this._handle_input_41_0.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_41,'blur',this.eventHandler(this._handle_blur_41_1.bind(this)));
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    var disposable_13:Function = this.renderer.listen(this._el_50,'input',this.eventHandler(this._handle_input_50_0.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_50,'blur',this.eventHandler(this._handle_blur_50_1.bind(this)));
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_57,'input',this.eventHandler(this._handle_input_57_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_57,'blur',this.eventHandler(this._handle_blur_57_1.bind(this)));
    this._expr_71 = import7.UNINITIALIZED;
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_75 = import7.UNINITIALIZED;
    this._expr_76 = import7.UNINITIALIZED;
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (6 === requestNodeIndex))) { return this._DefaultValueAccessor_6_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (6 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_6_4; }
    if (((token === import14.NgModel) && (6 === requestNodeIndex))) { return this._NgModel_6_5; }
    if (((token === import17.NgControl) && (6 === requestNodeIndex))) { return this._NgControl_6_6; }
    if (((token === import12.NgControlStatus) && (6 === requestNodeIndex))) { return this._NgControlStatus_6_7; }
    if (((token === import13.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import14.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_5; }
    if (((token === import17.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import12.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7; }
    if (((token === import13.DefaultValueAccessor) && (20 === requestNodeIndex))) { return this._DefaultValueAccessor_20_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_4; }
    if (((token === import14.NgModel) && (20 === requestNodeIndex))) { return this._NgModel_20_5; }
    if (((token === import17.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_6; }
    if (((token === import12.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_7; }
    if (((token === import13.DefaultValueAccessor) && (31 === requestNodeIndex))) { return this._DefaultValueAccessor_31_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_4; }
    if (((token === import14.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_5; }
    if (((token === import17.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_6; }
    if (((token === import12.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_7; }
    if (((token === import13.DefaultValueAccessor) && (41 === requestNodeIndex))) { return this._DefaultValueAccessor_41_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (41 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_41_4; }
    if (((token === import14.NgModel) && (41 === requestNodeIndex))) { return this._NgModel_41_5; }
    if (((token === import17.NgControl) && (41 === requestNodeIndex))) { return this._NgControl_41_6; }
    if (((token === import12.NgControlStatus) && (41 === requestNodeIndex))) { return this._NgControlStatus_41_7; }
    if (((token === import13.DefaultValueAccessor) && (50 === requestNodeIndex))) { return this._DefaultValueAccessor_50_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (50 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_50_4; }
    if (((token === import14.NgModel) && (50 === requestNodeIndex))) { return this._NgModel_50_5; }
    if (((token === import17.NgControl) && (50 === requestNodeIndex))) { return this._NgControl_50_6; }
    if (((token === import12.NgControlStatus) && (50 === requestNodeIndex))) { return this._NgControlStatus_50_7; }
    if (((token === import13.DefaultValueAccessor) && (57 === requestNodeIndex))) { return this._DefaultValueAccessor_57_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (57 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_57_4; }
    if (((token === import14.NgModel) && (57 === requestNodeIndex))) { return this._NgModel_57_5; }
    if (((token === import17.NgControl) && (57 === requestNodeIndex))) { return this._NgControl_57_6; }
    if (((token === import12.NgControlStatus) && (57 === requestNodeIndex))) { return this._NgControlStatus_57_7; }
    if (((token === import11.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NgForm_0_3; }
    if (((token === import18.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ControlContainer_0_4; }
    if (((token === import12.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_11:any = 'name';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgModel_6_5.name = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.name);
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_6_5.model = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._NgModel_6_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = 'position';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgModel_13_5.name = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.position);
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._NgModel_13_5.model = currVal_22;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_22,currVal_22);
      this._expr_22 = currVal_22;
    }
    if ((changes !== (null as any))) { this._NgModel_13_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_31:any = 'place';
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgModel_20_5.name = currVal_31;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_31,currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.place);
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgModel_20_5.model = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    if ((changes !== (null as any))) { this._NgModel_20_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_41:any = 'contact';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._NgModel_31_5.name = currVal_41;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_41,currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.contact);
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._NgModel_31_5.model = currVal_42;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_42,currVal_42);
      this._expr_42 = currVal_42;
    }
    if ((changes !== (null as any))) { this._NgModel_31_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_51:any = 'country';
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this._NgModel_41_5.name = currVal_51;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_51,currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.country);
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._NgModel_41_5.model = currVal_52;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_52,currVal_52);
      this._expr_52 = currVal_52;
    }
    if ((changes !== (null as any))) { this._NgModel_41_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_61:any = 'detail';
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this._NgModel_50_5.name = currVal_61;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_61,currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.detail);
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this._NgModel_50_5.model = currVal_62;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_62,currVal_62);
      this._expr_62 = currVal_62;
    }
    if ((changes !== (null as any))) { this._NgModel_50_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_71:any = 'misc';
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this._NgModel_57_5.name = currVal_71;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_71,currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_72:any = ((this.context.scholar == (null as any))? (null as any): this.context.scholar.misc);
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this._NgModel_57_5.model = currVal_72;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_72,currVal_72);
      this._expr_72 = currVal_72;
    }
    if ((changes !== (null as any))) { this._NgModel_57_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = this._NgControlStatus_6_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_6_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_6_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_6_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_6_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_6_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_23:any = this._NgControlStatus_13_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_13_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_13_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_13_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_13_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_13_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_33:any = this._NgControlStatus_20_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_20_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_20_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_20_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_20_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_20_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_43:any = this._NgControlStatus_31_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_31,'ng-untouched',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_31_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_31,'ng-touched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_31_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_31,'ng-pristine',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_31_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_31,'ng-dirty',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_31_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_31,'ng-valid',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_31_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_31,'ng-invalid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_53:any = this._NgControlStatus_41_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_41,'ng-untouched',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_41_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_41,'ng-touched',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_41_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_41,'ng-pristine',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_41_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_41,'ng-dirty',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_41_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_41,'ng-valid',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_41_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_41,'ng-invalid',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_63:any = this._NgControlStatus_50_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this.renderer.setElementClass(this._el_50,'ng-untouched',currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = this._NgControlStatus_50_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_50,'ng-touched',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_50_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_50,'ng-pristine',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_50_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_50,'ng-dirty',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_50_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_50,'ng-valid',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_50_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_50,'ng-invalid',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_73:any = this._NgControlStatus_57_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementClass(this._el_57,'ng-untouched',currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this._NgControlStatus_57_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementClass(this._el_57,'ng-touched',currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = this._NgControlStatus_57_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementClass(this._el_57,'ng-pristine',currVal_75);
      this._expr_75 = currVal_75;
    }
    const currVal_76:any = this._NgControlStatus_57_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setElementClass(this._el_57,'ng-dirty',currVal_76);
      this._expr_76 = currVal_76;
    }
    const currVal_77:any = this._NgControlStatus_57_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementClass(this._el_57,'ng-valid',currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = this._NgControlStatus_57_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementClass(this._el_57,'ng-invalid',currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:boolean = !this._NgForm_0_3.valid;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementProperty(this._el_62,'disabled',currVal_79);
      this._expr_79 = currVal_79;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_6_5.ngOnDestroy();
    this._NgModel_13_5.ngOnDestroy();
    this._NgModel_20_5.ngOnDestroy();
    this._NgModel_31_5.ngOnDestroy();
    this._NgModel_41_5.ngOnDestroy();
    this._NgModel_50_5.ngOnDestroy();
    this._NgModel_57_5.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_0_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_20_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_20_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_31_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_31_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_31_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_41_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_41_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_41_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_41_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_50_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_50_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_50_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_57_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_57_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_57_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_57_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ScholarFormComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ScholarFormComponent> {
  if ((renderType_ScholarFormComponent === (null as any))) { (renderType_ScholarFormComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/scholar/scholar-form.component.html',0,import9.ViewEncapsulation.None,styles_ScholarFormComponent,{})); }
  return new _View_ScholarFormComponent0(viewUtils,parentInjector,declarationEl);
}