/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './scholar-shell.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './scholar-form.component';
import * as import11 from './scholar-list.component';
import * as import12 from './scholar-form.component.ngfactory';
import * as import13 from './scholar.service';
import * as import14 from './scholar-list.component.ngfactory';
var renderType_ScholarShellComponent_Host:import0.RenderComponentType = (null as any);
class _View_ScholarShellComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScholarShellComponent_0_4:import3.ScholarShellComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarShellComponent_Host0,renderType_ScholarShellComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-scholar',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScholarShellComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScholarShellComponent_0_4 = new import3.ScholarShellComponent();
    this._appEl_0.initComponent(this._ScholarShellComponent_0_4,[],compView_0);
    compView_0.create(this._ScholarShellComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ScholarShellComponent) && (0 === requestNodeIndex))) { return this._ScholarShellComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ScholarShellComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ScholarShellComponent_Host === (null as any))) { (renderType_ScholarShellComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ScholarShellComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScholarShellComponentNgFactory:import9.ComponentFactory<import3.ScholarShellComponent> = new import9.ComponentFactory<import3.ScholarShellComponent>('app-scholar',viewFactory_ScholarShellComponent_Host0,import3.ScholarShellComponent);
const styles_ScholarShellComponent:any[] = ['#list-to-edit[_ngcontent-%COMP%] {\nheight: 100vh;\noverflow-y: scroll;'];
var renderType_ScholarShellComponent:import0.RenderComponentType = (null as any);
class _View_ScholarShellComponent0 extends import1.AppView<import3.ScholarShellComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ScholarFormComponent_4_4:import10.ScholarFormComponent;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _ScholarListComponent_9_4:import11.ScholarListComponent;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarShellComponent0,renderType_ScholarShellComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-sm-6');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'scholar-form',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import12.viewFactory_ScholarFormComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ScholarFormComponent_4_4 = new import10.ScholarFormComponent(this.parentInjector.get(import13.ScholarService));
    this._appEl_4.initComponent(this._ScholarFormComponent_4_4,[],compView_4);
    compView_4.create(this._ScholarFormComponent_4_4,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','col-sm-6');
    this.renderer.setElementAttribute(this._el_7,'id','list-to-edit');
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'scholar-list',(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._el_9);
    var compView_9:any = import14.viewFactory_ScholarListComponent0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ScholarListComponent_9_4 = new import11.ScholarListComponent(this.parentInjector.get(import13.ScholarService));
    this._appEl_9.initComponent(this._ScholarListComponent_9_4,[],compView_9);
    compView_9.create(this._ScholarListComponent_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.ScholarFormComponent) && (4 === requestNodeIndex))) { return this._ScholarFormComponent_4_4; }
    if (((token === import11.ScholarListComponent) && (9 === requestNodeIndex))) { return this._ScholarListComponent_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScholarFormComponent_4_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScholarListComponent_9_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ScholarShellComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ScholarShellComponent> {
  if ((renderType_ScholarShellComponent === (null as any))) { (renderType_ScholarShellComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/scholar/scholar-shell.component.ts class ScholarShellComponent - inline template',0,import8.ViewEncapsulation.Emulated,styles_ScholarShellComponent,{})); }
  return new _View_ScholarShellComponent0(viewUtils,parentInjector,declarationEl);
}