/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './scholar-list.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './scholar.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from './scholar-item.component';
import * as import15 from './scholar-item.component.ngfactory';
var renderType_ScholarListComponent_Host:import0.RenderComponentType = (null as any);
class _View_ScholarListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScholarListComponent_0_4:import3.ScholarListComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarListComponent_Host0,renderType_ScholarListComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('scholar-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScholarListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScholarListComponent_0_4 = new import3.ScholarListComponent(this.parentInjector.get(import8.ScholarService));
    this._appEl_0.initComponent(this._ScholarListComponent_0_4,[],compView_0);
    compView_0.create(this._ScholarListComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ScholarListComponent) && (0 === requestNodeIndex))) { return this._ScholarListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScholarListComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScholarListComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ScholarListComponent_Host === (null as any))) { (renderType_ScholarListComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ScholarListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScholarListComponentNgFactory:import10.ComponentFactory<import3.ScholarListComponent> = new import10.ComponentFactory<import3.ScholarListComponent>('scholar-list',viewFactory_ScholarListComponent_Host0,import3.ScholarListComponent);
const styles_ScholarListComponent:any[] = [];
var renderType_ScholarListComponent:import0.RenderComponentType = (null as any);
class _View_ScholarListComponent0 extends import1.AppView<import3.ScholarListComponent> {
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_5:any;
  _NgFor_0_6:import11.NgFor;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarListComponent0,renderType_ScholarListComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import12.TemplateRef_(this._appEl_0,viewFactory_ScholarListComponent1);
    this._NgFor_0_6 = new import11.NgFor(this._appEl_0.vcRef,this._TemplateRef_0_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[this._anchor_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import11.NgFor) && (0 === requestNodeIndex))) { return this._NgFor_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.scholars;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_0_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_0_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_0_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ScholarListComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ScholarListComponent> {
  if ((renderType_ScholarListComponent === (null as any))) { (renderType_ScholarListComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/scholar/scholar-list.component.html',0,import9.ViewEncapsulation.None,styles_ScholarListComponent,{})); }
  return new _View_ScholarListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ScholarListComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScholarItemComponent_0_4:import14.ScholarItemComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarListComponent1,renderType_ScholarListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'scholar-item',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import15.viewFactory_ScholarItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScholarItemComponent_0_4 = new import14.ScholarItemComponent(this.parentInjector.get(import8.ScholarService));
    this._appEl_0.initComponent(this._ScholarItemComponent_0_4,[],compView_0);
    compView_0.create(this._ScholarItemComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ScholarItemComponent) && (0 === requestNodeIndex))) { return this._ScholarItemComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ScholarItemComponent_0_4.scholar = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ScholarListComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ScholarListComponent1(viewUtils,parentInjector,declarationEl);
}