/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './scholar-item.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './scholar.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
var renderType_ScholarItemComponent_Host:import0.RenderComponentType = (null as any);
class _View_ScholarItemComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScholarItemComponent_0_4:import3.ScholarItemComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarItemComponent_Host0,renderType_ScholarItemComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('scholar-item',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ScholarItemComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScholarItemComponent_0_4 = new import3.ScholarItemComponent(this.parentInjector.get(import8.ScholarService));
    this._appEl_0.initComponent(this._ScholarItemComponent_0_4,[],compView_0);
    compView_0.create(this._ScholarItemComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ScholarItemComponent) && (0 === requestNodeIndex))) { return this._ScholarItemComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ScholarItemComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ScholarItemComponent_Host === (null as any))) { (renderType_ScholarItemComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ScholarItemComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ScholarItemComponentNgFactory:import10.ComponentFactory<import3.ScholarItemComponent> = new import10.ComponentFactory<import3.ScholarItemComponent>('scholar-item',viewFactory_ScholarItemComponent_Host0,import3.ScholarItemComponent);
const styles_ScholarItemComponent:any[] = [];
var renderType_ScholarItemComponent:import0.RenderComponentType = (null as any);
class _View_ScholarItemComponent0 extends import1.AppView<import3.ScholarItemComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ScholarItemComponent0,renderType_ScholarItemComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-header text-center');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-title');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'h6',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','card-subtitle mb-2 text-muted');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','card-block');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'p',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','card-text');
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'p',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','card-text');
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_11,'h6',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','card-subtitle mb-2 text-muted');
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','card-footer text-muted text-center');
    this._text_24 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','btn btn-outline-primary');
    this._text_26 = this.renderer.createText(this._el_25,'Edit',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','btn btn-outline-danger');
    this._text_29 = this.renderer.createText(this._el_28,'Delete',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.scholar.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(2,'',this.context.scholar.position,', ',this.context.scholar.place,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_8,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'Detail: ',this.context.scholar.detail,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_14,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'Detail: ',this.context.scholar.misc,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_17,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.scholar.contact,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_20,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onEdit()) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDelete()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ScholarItemComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ScholarItemComponent> {
  if ((renderType_ScholarItemComponent === (null as any))) { (renderType_ScholarItemComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/scholar/scholar-item.component.html',0,import9.ViewEncapsulation.None,styles_ScholarItemComponent,{})); }
  return new _View_ScholarItemComponent0(viewUtils,parentInjector,declarationEl);
}