/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../scholar/scholar.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_HomeComponent_Host:import0.RenderComponentType = (null as any);
class _View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomeComponent_0_4:import3.HomeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomeComponent_Host0,renderType_HomeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomeComponent_0_4 = new import3.HomeComponent(this.parentInjector.get(import8.ScholarService));
    this._appEl_0.initComponent(this._HomeComponent_0_4,[],compView_0);
    compView_0.create(this._HomeComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HomeComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomeComponent_Host === (null as any))) { (renderType_HomeComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_HomeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomeComponentNgFactory:import10.ComponentFactory<import3.HomeComponent> = new import10.ComponentFactory<import3.HomeComponent>('app-home',viewFactory_HomeComponent_Host0,import3.HomeComponent);
const styles_HomeComponent:any[] = ['.home[_ngcontent-%COMP%] {\n    height: 100vh;\n    width: 100%;\n    background: rgba(0,0,0,.7);\n    }'];
var renderType_HomeComponent:import0.RenderComponentType = (null as any);
class _View_HomeComponent0 extends import1.AppView<import3.HomeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import11.NgFor;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import12.NgIf;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import12.NgIf;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomeComponent0,renderType_HomeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','home');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','jumbotron');
    this.renderer.setElementAttribute(this._el_2,'style','margin-top: -33px; padding: 40px 0 37px 20px;');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','display-2');
    this._text_5 = this.renderer.createText(this._el_4,'\n            Sorokiniana ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-muted');
    this._text_7 = this.renderer.createText(this._el_6,'continues...',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_10,'alt','');
    this.renderer.setElementAttribute(this._el_10,'class','rounded float-right');
    this.renderer.setElementAttribute(this._el_10,'height','230px');
    this.renderer.setElementAttribute(this._el_10,'src','/images/pas3.png');
    this.renderer.setElementAttribute(this._el_10,'style','margin-top: -125px;');
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','container');
    this._el_14 = this.renderer.createElement(this._el_13,'h3',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'Scholars:',(null as any));
    this._text_16 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','row');
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','col-sm-4');
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_21 = new import2.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import13.TemplateRef_(this._appEl_21,viewFactory_HomeComponent1);
    this._NgFor_21_6 = new import11.NgFor(this._appEl_21.vcRef,this._TemplateRef_21_5,this.parentInjector.get(import14.IterableDiffers),this.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._appEl_24 = new import2.AppElement(24,17,this,this._anchor_24);
    this._TemplateRef_24_5 = new import13.TemplateRef_(this._appEl_24,viewFactory_HomeComponent2);
    this._NgIf_24_6 = new import12.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_17,(null as any));
    this._appEl_26 = new import2.AppElement(26,17,this,this._anchor_26);
    this._TemplateRef_26_5 = new import13.TemplateRef_(this._appEl_26,viewFactory_HomeComponent3);
    this._NgIf_26_6 = new import12.NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_13,'\n\n\n    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import11.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6; }
    if (((token === import13.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import12.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import13.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import12.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.scholars;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_21_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_21_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_21_6.ngDoCheck(); }
    const currVal_1:any = this.context.selectedScholar;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_24_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:boolean = !this.context.selectedScholar;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_26_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_HomeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomeComponent> {
  if ((renderType_HomeComponent === (null as any))) { (renderType_HomeComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/home/home.component.html',0,import9.ViewEncapsulation.Emulated,styles_HomeComponent,{})); }
  return new _View_HomeComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomeComponent1,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','thelist');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = (this.context.$implicit == this.parent.context.selectedScholar);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'selected',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(2,'\n                    ',this.context.$implicit.name,' (',this.context.$implicit.country,')\n                ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSelect(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomeComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomeComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomeComponent2,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-sm-7');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card card-outline-warning mb-3');
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','card-block');
    this.renderer.setElementAttribute(this._el_4,'style','color: cornsilk');
    this._text_5 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-center');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'span',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','card-text');
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','card-text');
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_4,'blockquote',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','card-blockquote');
    this._text_19 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'p',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'footer',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'Someone famous in ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'cite',(null as any));
    this.renderer.setElementAttribute(this._el_25,'title','Source Title');
    this._text_26 = this.renderer.createText(this._el_25,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(2,'',this.parent.context.selectedScholar.name,', ',this.parent.context.selectedScholar.place,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.selectedScholar.position,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'Link to Sorokin: ',this.parent.context.selectedScholar.detail,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_13,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'About: ',this.parent.context.selectedScholar.misc,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_16,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.parent.context.selectedScholar.contact,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_21,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.parent.context.selectedScholar.contact,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_26,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomeComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomeComponent3,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-sm-6');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h3',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Some other text before clicked',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_HomeComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomeComponent3(viewUtils,parentInjector,declarationEl);
}