/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './auth-shell.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/router/src/directives/router_link';
import * as import11 from '@angular/router/src/directives/router_link_active';
import * as import12 from '@angular/core/src/linker/query_list';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '@angular/router/src/directives/router_outlet';
import * as import15 from '@angular/router/src/router';
import * as import16 from '@angular/router/src/router_state';
import * as import17 from '@angular/common/src/location/location_strategy';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/router/src/router_outlet_map';
import * as import21 from '@angular/core/src/linker/component_factory_resolver';
import * as import22 from '@angular/core/src/security';
var renderType_AuthComponent_Host:import0.RenderComponentType = (null as any);
class _View_AuthComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AuthComponent_0_4:import3.AuthComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthComponent_Host0,renderType_AuthComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-auth',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AuthComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AuthComponent_0_4 = new import3.AuthComponent();
    this._appEl_0.initComponent(this._AuthComponent_0_4,[],compView_0);
    compView_0.create(this._AuthComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AuthComponent) && (0 === requestNodeIndex))) { return this._AuthComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AuthComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AuthComponent_Host === (null as any))) { (renderType_AuthComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_AuthComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AuthComponentNgFactory:import9.ComponentFactory<import3.AuthComponent> = new import9.ComponentFactory<import3.AuthComponent>('app-auth',viewFactory_AuthComponent_Host0,import3.AuthComponent);
const styles_AuthComponent:any[] = [];
var renderType_AuthComponent:import0.RenderComponentType = (null as any);
class _View_AuthComponent0 extends import1.AppView<import3.AuthComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import10.RouterLinkWithHref;
  _RouterLinkActive_9_4:import11.RouterLinkActive;
  _query_RouterLink_9_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_9_1:import12.QueryList<any>;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import10.RouterLinkWithHref;
  _RouterLinkActive_15_4:import11.RouterLinkActive;
  _query_RouterLink_15_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import12.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _RouterLinkActive_19_3:import11.RouterLinkActive;
  _query_RouterLink_19_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_19_1:import12.QueryList<any>;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import13.NgIf;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _RouterOutlet_28_5:import14.RouterOutlet;
  _text_29:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _arr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthComponent0,renderType_AuthComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-md-6 offset-md-3');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Auth Component',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','nav nav-tabs');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'li',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','nav-item');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'a',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','nav-link');
    this.renderer.setElementAttribute(this._el_9,'routerLinkActive','active');
    this._RouterLinkWithHref_9_3 = new import10.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_9_4 = new import11.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_9),this.renderer);
    this._query_RouterLink_9_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_9_1 = new import12.QueryList<any>();
    this._text_10 = this.renderer.createText(this._el_9,'Register',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_5,'li',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','nav-item');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'a',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','nav-link');
    this.renderer.setElementAttribute(this._el_15,'routerLinkActive','active');
    this._RouterLinkWithHref_15_3 = new import10.RouterLinkWithHref(this.parentInjector.get(import15.Router),this.parentInjector.get(import16.ActivatedRoute),this.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_15_4 = new import11.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import12.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'Login',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_5,'li',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','nav-item');
    this.renderer.setElementAttribute(this._el_19,'routerLinkActive','active');
    this._RouterLinkActive_19_3 = new import11.RouterLinkActive(this.parentInjector.get(import15.Router),new import18.ElementRef(this._el_19),this.renderer);
    this._query_RouterLink_19_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_19_1 = new import12.QueryList<any>();
    this._text_20 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_21 = new import2.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import19.TemplateRef_(this._appEl_21,viewFactory_AuthComponent1);
    this._NgIf_21_6 = new import13.NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._el_26 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_0,'router-outlet',(null as any));
    this._appEl_28 = new import2.AppElement(28,0,this,this._el_28);
    this._RouterOutlet_28_5 = new import14.RouterOutlet(this.parentInjector.get(import20.RouterOutletMap),this._appEl_28.vcRef,this.parentInjector.get(import21.ComponentFactoryResolver),(null as any));
    this._text_29 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3; }
    if (((token === import11.RouterLinkActive) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkActive_9_4; }
    if (((token === import10.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3; }
    if (((token === import11.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4; }
    if (((token === import19.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import13.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6; }
    if (((token === import11.RouterLinkActive) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._RouterLinkActive_19_3; }
    if (((token === import14.RouterOutlet) && (28 === requestNodeIndex))) { return this._RouterOutlet_28_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('signup');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_9_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_9_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_9_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_9_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_5:any = this._arr_1('login');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_15_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_15_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkActive_15_4.routerLinkActive = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_15_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_8:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._RouterLinkActive_19_3.routerLinkActive = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_19_3.ngOnChanges(changes); }
    const currVal_9:any = this.context.hasToken();
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_21_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_9_0.dirty) {
        this._query_RouterLink_9_0.reset([]);
        this._RouterLinkActive_9_4.links = this._query_RouterLink_9_0;
        this._query_RouterLink_9_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_9_1.dirty) {
        this._query_RouterLinkWithHref_9_1.reset([this._RouterLinkWithHref_9_3]);
        this._RouterLinkActive_9_4.linksWithHrefs = this._query_RouterLinkWithHref_9_1;
        this._query_RouterLinkWithHref_9_1.notifyOnChanges();
      }
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset([]);
        this._RouterLinkActive_15_4.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3]);
        this._RouterLinkActive_15_4.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_19_0.dirty) {
        this._query_RouterLink_19_0.reset([]);
        this._RouterLinkActive_19_3.links = this._query_RouterLink_19_0;
        this._query_RouterLink_19_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_19_1.dirty) {
          this._query_RouterLinkWithHref_19_1.reset([this._appEl_21.mapNestedViews(_View_AuthComponent1,(nestedView:_View_AuthComponent1):any => {
            return [nestedView._RouterLinkWithHref_0_3];
        })]);
        this._RouterLinkActive_19_3.linksWithHrefs = this._query_RouterLinkWithHref_19_1;
        this._query_RouterLinkWithHref_19_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_9_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_19_3.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_9_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_9,'href',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._RouterLinkWithHref_15_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_9_3.ngOnDestroy();
    this._RouterLinkActive_9_4.ngOnDestroy();
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this._RouterLinkActive_15_4.ngOnDestroy();
    this._RouterLinkActive_19_3.ngOnDestroy();
    this._RouterOutlet_28_5.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_9_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_15_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AuthComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AuthComponent> {
  if ((renderType_AuthComponent === (null as any))) { (renderType_AuthComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/auth/auth-shell.component.html',0,import8.ViewEncapsulation.None,styles_AuthComponent,{})); }
  return new _View_AuthComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AuthComponent1 extends import1.AppView<any> {
  _el_0:any;
  _RouterLinkWithHref_0_3:import10.RouterLinkWithHref;
  _RouterLinkActive_0_4:import11.RouterLinkActive;
  _query_RouterLink_0_0:import12.QueryList<any>;
  _query_RouterLinkWithHref_0_1:import12.QueryList<any>;
  _text_1:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AuthComponent1,renderType_AuthComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','nav-link');
    this.renderer.setElementAttribute(this._el_0,'routerLinkActive','active');
    this._RouterLinkWithHref_0_3 = new import10.RouterLinkWithHref(this.parent.parentInjector.get(import15.Router),this.parent.parentInjector.get(import16.ActivatedRoute),this.parent.parentInjector.get(import17.LocationStrategy));
    this._RouterLinkActive_0_4 = new import11.RouterLinkActive(this.parent.parentInjector.get(import15.Router),new import18.ElementRef(this._el_0),this.renderer);
    this._query_RouterLink_0_0 = new import12.QueryList<any>();
    this._query_RouterLinkWithHref_0_1 = new import12.QueryList<any>();
    this._text_1 = this.renderer.createText(this._el_0,'Logout',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.RouterLinkWithHref) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkWithHref_0_3; }
    if (((token === import11.RouterLinkActive) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._RouterLinkActive_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this._arr_0('logout');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_0_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_0_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_0_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_0_0.dirty) {
        this._query_RouterLink_0_0.reset([]);
        this._RouterLinkActive_0_4.links = this._query_RouterLink_0_0;
        this._query_RouterLink_0_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_0_1.dirty) {
        this._query_RouterLinkWithHref_0_1.reset([this._RouterLinkWithHref_0_3]);
        this._RouterLinkActive_0_4.linksWithHrefs = this._query_RouterLinkWithHref_0_1;
        this._query_RouterLinkWithHref_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_0_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_0_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'href',this.viewUtils.sanitizer.sanitize(import22.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_AuthComponent0>this.parent)._query_RouterLinkWithHref_19_1.setDirty();
  }
  destroyInternal():void {
    this._RouterLinkWithHref_0_3.ngOnDestroy();
    this._RouterLinkActive_0_4.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_0_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_AuthComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AuthComponent1(viewUtils,parentInjector,declarationEl);
}