/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './login.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_control';
import * as import19 from '@angular/forms/src/directives/control_container';
var renderType_LoginComponent_Host:import0.RenderComponentType = (null as any);
class _View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginComponent_0_4:import3.LoginComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginComponent_Host0,renderType_LoginComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-login',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginComponent_0_4 = new import3.LoginComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._LoginComponent_0_4,[],compView_0);
    compView_0.create(this._LoginComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LoginComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginComponent_Host === (null as any))) { (renderType_LoginComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_LoginComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginComponentNgFactory:import11.ComponentFactory<import3.LoginComponent> = new import11.ComponentFactory<import3.LoginComponent>('app-login',viewFactory_LoginComponent_Host0,import3.LoginComponent);
const styles_LoginComponent:any[] = [];
var renderType_LoginComponent:import0.RenderComponentType = (null as any);
class _View_LoginComponent0 extends import1.AppView<import3.LoginComponent> {
  _el_0:any;
  _FormGroupDirective_0_3:import12.FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import13.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _DefaultValueAccessor_6_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_6_4:any[];
  _FormControlName_6_5:import15.FormControlName;
  _NgControl_6_6:any;
  _NgControlStatus_6_7:import13.NgControlStatus;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_13_4:any[];
  _FormControlName_13_5:import15.FormControlName;
  _NgControl_13_6:any;
  _NgControlStatus_13_7:import13.NgControlStatus;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginComponent0,renderType_LoginComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._FormGroupDirective_0_3 = new import12.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3;
    this._NgControlStatusGroup_0_5 = new import13.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','form-group');
    this._el_3 = this.renderer.createElement(this._el_2,'label',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Email',(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','form-control');
    this.renderer.setElementAttribute(this._el_6,'formControlName','email');
    this.renderer.setElementAttribute(this._el_6,'type','email');
    this._DefaultValueAccessor_6_3 = new import14.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_6));
    this._NG_VALUE_ACCESSOR_6_4 = [this._DefaultValueAccessor_6_3];
    this._FormControlName_6_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_6_4);
    this._NgControl_6_6 = this._FormControlName_6_5;
    this._NgControlStatus_6_7 = new import13.NgControlStatus(this._NgControl_6_6);
    this._text_7 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','form-group');
    this._el_10 = this.renderer.createElement(this._el_9,'label',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Password',(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_9,'input',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-control');
    this.renderer.setElementAttribute(this._el_13,'formControlName','password');
    this.renderer.setElementAttribute(this._el_13,'type','password');
    this._DefaultValueAccessor_13_3 = new import14.DefaultValueAccessor(this.renderer,new import16.ElementRef(this._el_13));
    this._NG_VALUE_ACCESSOR_13_4 = [this._DefaultValueAccessor_13_3];
    this._FormControlName_13_5 = new import15.FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_13_4);
    this._NgControl_13_6 = this._FormControlName_13_5;
    this._NgControlStatus_13_7 = new import13.NgControlStatus(this._NgControl_13_6);
    this._text_14 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-group');
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','btn btn-outline-primary');
    this.renderer.setElementAttribute(this._el_18,'type','submit');
    this._text_19 = this.renderer.createText(this._el_18,'Submit',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_6,'input',this.eventHandler(this._handle_input_6_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_6,'blur',this.eventHandler(this._handle_blur_6_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_1.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (6 === requestNodeIndex))) { return this._DefaultValueAccessor_6_3; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (6 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_6_4; }
    if (((token === import15.FormControlName) && (6 === requestNodeIndex))) { return this._FormControlName_6_5; }
    if (((token === import18.NgControl) && (6 === requestNodeIndex))) { return this._NgControl_6_6; }
    if (((token === import13.NgControlStatus) && (6 === requestNodeIndex))) { return this._NgControlStatus_6_7; }
    if (((token === import14.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_4; }
    if (((token === import15.FormControlName) && (13 === requestNodeIndex))) { return this._FormControlName_13_5; }
    if (((token === import18.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_6; }
    if (((token === import13.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_7; }
    if (((token === import12.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._FormGroupDirective_0_3; }
    if (((token === import19.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ControlContainer_0_4; }
    if (((token === import13.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_0_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_0_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_6_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_6_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._FormControlName_13_5.name = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._FormControlName_13_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._NgControlStatus_6_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_6_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_6_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_6_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_6_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_6_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._NgControlStatus_13_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_13_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_13_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_13_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_13_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_13_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:boolean = !this.context.myForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementProperty(this._el_18,'disabled',currVal_28);
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_6_5.ngOnDestroy();
    this._FormControlName_13_5.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_13_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginComponent> {
  if ((renderType_LoginComponent === (null as any))) { (renderType_LoginComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/auth/login.component.html',0,import10.ViewEncapsulation.None,styles_LoginComponent,{})); }
  return new _View_LoginComponent0(viewUtils,parentInjector,declarationEl);
}