/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './signup.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from '@angular/forms/src/directives/default_value_accessor';
import * as import14 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/forms/src/directives/control_value_accessor';
import * as import17 from '@angular/forms/src/directives/ng_control';
import * as import18 from '@angular/forms/src/directives/control_container';
var renderType_SignupComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignupComponent_0_4:import3.SignupComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent_Host0,renderType_SignupComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-signup',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupComponent_0_4 = new import3.SignupComponent(this.parentInjector.get(import8.AuthService));
    this._appEl_0.initComponent(this._SignupComponent_0_4,[],compView_0);
    compView_0.create(this._SignupComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignupComponent) && (0 === requestNodeIndex))) { return this._SignupComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SignupComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignupComponent_Host === (null as any))) { (renderType_SignupComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_SignupComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupComponentNgFactory:import10.ComponentFactory<import3.SignupComponent> = new import10.ComponentFactory<import3.SignupComponent>('app-signup',viewFactory_SignupComponent_Host0,import3.SignupComponent);
const styles_SignupComponent:any[] = [];
var renderType_SignupComponent:import0.RenderComponentType = (null as any);
class _View_SignupComponent0 extends import1.AppView<import3.SignupComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import11.FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import12.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _DefaultValueAccessor_8_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_8_4:any[];
  _FormControlName_8_5:import14.FormControlName;
  _NgControl_8_6:any;
  _NgControlStatus_8_7:import12.NgControlStatus;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _DefaultValueAccessor_15_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_15_4:any[];
  _FormControlName_15_5:import14.FormControlName;
  _NgControl_15_6:any;
  _NgControlStatus_15_7:import12.NgControlStatus;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _FormControlName_22_5:import14.FormControlName;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import12.NgControlStatus;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _DefaultValueAccessor_29_3:import13.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_29_4:any[];
  _FormControlName_29_5:import14.FormControlName;
  _NgControl_29_6:any;
  _NgControlStatus_29_7:import12.NgControlStatus;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent0,renderType_SignupComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._FormGroupDirective_2_3 = new import11.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3;
    this._NgControlStatusGroup_2_5 = new import12.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','form-group');
    this._el_5 = this.renderer.createElement(this._el_4,'label',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'First Name',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_4,'input',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','form-control');
    this.renderer.setElementAttribute(this._el_8,'formControlName','firstName');
    this.renderer.setElementAttribute(this._el_8,'type','text');
    this._DefaultValueAccessor_8_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_8));
    this._NG_VALUE_ACCESSOR_8_4 = [this._DefaultValueAccessor_8_3];
    this._FormControlName_8_5 = new import14.FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_8_4);
    this._NgControl_8_6 = this._FormControlName_8_5;
    this._NgControlStatus_8_7 = new import12.NgControlStatus(this._NgControl_8_6);
    this._text_9 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form-group');
    this._el_12 = this.renderer.createElement(this._el_11,'label',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Last Name',(null as any));
    this._text_14 = this.renderer.createText(this._el_11,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_11,'input',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','form-control');
    this.renderer.setElementAttribute(this._el_15,'formControlName','lastName');
    this.renderer.setElementAttribute(this._el_15,'type','text');
    this._DefaultValueAccessor_15_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_15));
    this._NG_VALUE_ACCESSOR_15_4 = [this._DefaultValueAccessor_15_3];
    this._FormControlName_15_5 = new import14.FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_15_4);
    this._NgControl_15_6 = this._FormControlName_15_5;
    this._NgControlStatus_15_7 = new import12.NgControlStatus(this._NgControl_15_6);
    this._text_16 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-group');
    this._el_19 = this.renderer.createElement(this._el_18,'label',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'Email',(null as any));
    this._text_21 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_18,'input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-control');
    this.renderer.setElementAttribute(this._el_22,'formControlName','email');
    this.renderer.setElementAttribute(this._el_22,'type','email');
    this._DefaultValueAccessor_22_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._DefaultValueAccessor_22_3];
    this._FormControlName_22_5 = new import14.FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._FormControlName_22_5;
    this._NgControlStatus_22_7 = new import12.NgControlStatus(this._NgControl_22_6);
    this._text_23 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-group');
    this._el_26 = this.renderer.createElement(this._el_25,'label',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Password',(null as any));
    this._text_28 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_25,'input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-control');
    this.renderer.setElementAttribute(this._el_29,'formControlName','password');
    this.renderer.setElementAttribute(this._el_29,'type','password');
    this._DefaultValueAccessor_29_3 = new import13.DefaultValueAccessor(this.renderer,new import15.ElementRef(this._el_29));
    this._NG_VALUE_ACCESSOR_29_4 = [this._DefaultValueAccessor_29_3];
    this._FormControlName_29_5 = new import14.FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_29_4);
    this._NgControl_29_6 = this._FormControlName_29_5;
    this._NgControlStatus_29_7 = new import12.NgControlStatus(this._NgControl_29_6);
    this._text_30 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-group');
    this._text_33 = this.renderer.createText(this._el_32,'\n           ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'button',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','btn btn-outline-primary');
    this.renderer.setElementAttribute(this._el_34,'type','submit');
    this._text_35 = this.renderer.createText(this._el_34,'Submit',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_37 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._FormGroupDirective_2_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_8,'input',this.eventHandler(this._handle_input_8_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_8,'blur',this.eventHandler(this._handle_blur_8_1.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_15,'input',this.eventHandler(this._handle_input_15_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_15,'blur',this.eventHandler(this._handle_blur_15_1.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_22,'input',this.eventHandler(this._handle_input_22_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_22,'blur',this.eventHandler(this._handle_blur_22_1.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_29,'input',this.eventHandler(this._handle_input_29_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_29,'blur',this.eventHandler(this._handle_blur_29_1.bind(this)));
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.DefaultValueAccessor) && (8 === requestNodeIndex))) { return this._DefaultValueAccessor_8_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_4; }
    if (((token === import14.FormControlName) && (8 === requestNodeIndex))) { return this._FormControlName_8_5; }
    if (((token === import17.NgControl) && (8 === requestNodeIndex))) { return this._NgControl_8_6; }
    if (((token === import12.NgControlStatus) && (8 === requestNodeIndex))) { return this._NgControlStatus_8_7; }
    if (((token === import13.DefaultValueAccessor) && (15 === requestNodeIndex))) { return this._DefaultValueAccessor_15_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (15 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_15_4; }
    if (((token === import14.FormControlName) && (15 === requestNodeIndex))) { return this._FormControlName_15_5; }
    if (((token === import17.NgControl) && (15 === requestNodeIndex))) { return this._NgControl_15_6; }
    if (((token === import12.NgControlStatus) && (15 === requestNodeIndex))) { return this._NgControlStatus_15_7; }
    if (((token === import13.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import14.FormControlName) && (22 === requestNodeIndex))) { return this._FormControlName_22_5; }
    if (((token === import17.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import12.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7; }
    if (((token === import13.DefaultValueAccessor) && (29 === requestNodeIndex))) { return this._DefaultValueAccessor_29_3; }
    if (((token === import16.NG_VALUE_ACCESSOR) && (29 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_29_4; }
    if (((token === import14.FormControlName) && (29 === requestNodeIndex))) { return this._FormControlName_29_5; }
    if (((token === import17.NgControl) && (29 === requestNodeIndex))) { return this._NgControl_29_6; }
    if (((token === import12.NgControlStatus) && (29 === requestNodeIndex))) { return this._NgControlStatus_29_7; }
    if (((token === import11.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._FormGroupDirective_2_3; }
    if (((token === import18.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ControlContainer_2_4; }
    if (((token === import12.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.myForm;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._FormGroupDirective_2_3.form = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_2_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_12:any = 'firstName';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._FormControlName_8_5.name = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._FormControlName_8_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = 'lastName';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._FormControlName_15_5.name = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._FormControlName_15_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_30:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._FormControlName_22_5.name = currVal_30;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_30,currVal_30);
      this._expr_30 = currVal_30;
    }
    if ((changes !== (null as any))) { this._FormControlName_22_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_39:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._FormControlName_29_5.name = currVal_39;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_39,currVal_39);
      this._expr_39 = currVal_39;
    }
    if ((changes !== (null as any))) { this._FormControlName_29_5.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_13:any = this._NgControlStatus_8_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_8,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_8_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_8,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_8_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_8,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_8_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_8,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_8_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_8,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_8_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_8,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._NgControlStatus_15_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_15,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_15_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_15,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_15_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_15,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_15_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_15,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_15_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_15,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_15_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_15,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_31:any = this._NgControlStatus_22_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_22_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_22_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_22_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_22_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_22_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_40:any = this._NgControlStatus_29_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_29,'ng-untouched',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_29_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_29,'ng-touched',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_29_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_29,'ng-pristine',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_29_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_29,'ng-dirty',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_29_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_29,'ng-valid',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_29_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_29,'ng-invalid',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:boolean = !this.context.myForm.valid;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementProperty(this._el_34,'disabled',currVal_46);
      this._expr_46 = currVal_46;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._FormControlName_8_5.ngOnDestroy();
    this._FormControlName_15_5.ngOnDestroy();
    this._FormControlName_22_5.ngOnDestroy();
    this._FormControlName_29_5.ngOnDestroy();
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_8_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_8_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_8_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_15_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_15_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_15_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_22_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_22_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_29_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_29_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_29_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignupComponent> {
  if ((renderType_SignupComponent === (null as any))) { (renderType_SignupComponent = viewUtils.createRenderComponentType('/Users/pavelkrotov/Code/angular-express/assets/app/auth/signup.component.html',0,import9.ViewEncapsulation.None,styles_SignupComponent,{})); }
  return new _View_SignupComponent0(viewUtils,parentInjector,declarationEl);
}